# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bareMinimum.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 298)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, -1, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 10, 20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(172, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logo/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.KimoFile = QtWidgets.QLineEdit(self.centralwidget)
        self.KimoFile.setEnabled(True)
        self.KimoFile.setObjectName("KimoFile")
        self.horizontalLayout_3.addWidget(self.KimoFile)
        self.OpenKimo = QtWidgets.QPushButton(self.centralwidget)
        self.OpenKimo.setObjectName("OpenKimo")
        self.horizontalLayout_3.addWidget(self.OpenKimo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ExcelFile = QtWidgets.QLineEdit(self.centralwidget)
        self.ExcelFile.setEnabled(True)
        self.ExcelFile.setObjectName("ExcelFile")
        self.horizontalLayout.addWidget(self.ExcelFile)
        self.OpenExcel = QtWidgets.QPushButton(self.centralwidget)
        self.OpenExcel.setObjectName("OpenExcel")
        self.horizontalLayout.addWidget(self.OpenExcel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.EditExcel = QtWidgets.QPushButton(self.centralwidget)
        self.EditExcel.setObjectName("EditExcel")
        self.horizontalLayout_2.addWidget(self.EditExcel)
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setObjectName("Save")
        self.horizontalLayout_2.addWidget(self.Save)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("margin-right:-10px;")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.KimoFile.setPlaceholderText(_translate("MainWindow", "Select Kimo Data File (*.kfk)"))
        self.OpenKimo.setText(_translate("MainWindow", "Browse"))
        self.ExcelFile.setPlaceholderText(_translate("MainWindow", "Select Source Excel File (*.xlsx)"))
        self.OpenExcel.setText(_translate("MainWindow", "Browse"))
        self.EditExcel.setText(_translate("MainWindow", "Edit"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Made with ❤ by Saikat.c"))
import resources_rc
